quarkus:
  http:
    host-enabled: false
  log:
    level: ERROR
  banner:
    enabled: false
  package:
    type: 'native'
  native:
    additional-build-args:
      - '-H:EnableURLProtocols=http,https'
      - '-H:ResourceConfigurationFiles=resources-config.json'
      - '-H:ReflectionConfigurationFiles=reflection-config.json'
      - '-H:-CheckToolchain'
      - '--initialize-at-run-time=cash.z.ecc.android.bip39.Mnemonics'
