quarkus:
  log:
    level: ERROR
  banner:
    enabled: false
  package:
    type: 'native'
  native:
    resources:
      inlcudes:
        - 'mnemonic/wordlist/english.txt'
    additional-build-args:
      - '-H:EnableURLProtocols=http,https'
      - '-H:-CheckToolchain'