version: "3"

services:
  ddc-node-0:
    container_name: 'ddc-node-0'
    image: '338287888375.dkr.ecr.us-west-2.amazonaws.com/ddc-node:v0.27.0'
    environment:
      - 'HTTP_PORT=8080'
      - 'REMOTE_HTTP_ADDR=http://localhost:8080'
      - 'P2P_LISTEN_ADDR=/dns4/ddc-node-0/tcp/5000'
      - 'LOG_LEVEL=debug'
      - 'HEARTBEAT_INTERVAL_IN_SECONDS=1'
      - 'UPDATE_NEIGHBORS_INTERVAL_IN_SECONDS=1'
      - 'SHORT_TRANSIENT_FAULT_TIMEOUT_IN_SECONDS=4'
      - 'LONG_TRANSIENT_FAULT_TIMEOUT_IN_SECONDS=20'
      - 'COMPLETE_FAULT_TIMEOUT_IN_SECONDS=40'
      - 'PARTITIONS=50'
      - 'PARTITION_SIZE_LIMIT_IN_BYTES=100000000'
      - 'PARTITION_WCU_LIMIT=180000000'
      - 'PARTITION_RCU_LIMIT=450000000'
      - 'TEST_MODE=true'
      - 'DDC_MOCK_APP_LIMIT={"storageBytes":100000000,"wcu":90000000,"rcu":225000000}'
      - 'DDC_MOCK_ALL_DDC_NODES=${DDC_MOCK_ALL_DDC_NODES}'
    ports:
      - '5000:5000'
      - '8080:8080'
    volumes:
      - ./node-0-p2p-config.json:/config/p2p.json
  ddc-node-1:
    container_name: 'ddc-node-1'
    image: '338287888375.dkr.ecr.us-west-2.amazonaws.com/ddc-node:v0.27.0'
    environment:
      - 'HTTP_PORT=8081'
      - 'REMOTE_HTTP_ADDR=http://localhost:8081'
      - 'P2P_LISTEN_ADDR=/dns4/ddc-node-1/tcp/5001'
      - 'LOG_LEVEL=debug'
      - 'HEARTBEAT_INTERVAL_IN_SECONDS=1'
      - 'UPDATE_NEIGHBORS_INTERVAL_IN_SECONDS=1'
      - 'SHORT_TRANSIENT_FAULT_TIMEOUT_IN_SECONDS=4'
      - 'LONG_TRANSIENT_FAULT_TIMEOUT_IN_SECONDS=20'
      - 'COMPLETE_FAULT_TIMEOUT_IN_SECONDS=40'
      - 'PARTITIONS=50'
      - 'PARTITION_SIZE_LIMIT_IN_BYTES=100000000'
      - 'PARTITION_WCU_LIMIT=180000000'
      - 'PARTITION_RCU_LIMIT=450000000'
      - 'TEST_MODE=true'
      - 'DDC_MOCK_APP_LIMIT={"storageBytes":100000000,"wcu":90000000,"rcu":225000000}'
      - 'DDC_MOCK_ALL_DDC_NODES=${DDC_MOCK_ALL_DDC_NODES}'
    ports:
      - '5001:5001'
      - '8081:8081'
    volumes:
      - ./node-1-p2p-config.json:/config/p2p.json
    depends_on:
      - 'ddc-node-0'
  ddc-node-2:
    container_name: 'ddc-node-2'
    image: '338287888375.dkr.ecr.us-west-2.amazonaws.com/ddc-node:v0.27.0'
    environment:
      - 'HTTP_PORT=8082'
      - 'REMOTE_HTTP_ADDR=http://localhost:8082'
      - 'P2P_LISTEN_ADDR=/dns4/ddc-node-2/tcp/5002'
      - 'LOG_LEVEL=debug'
      - 'HEARTBEAT_INTERVAL_IN_SECONDS=1'
      - 'UPDATE_NEIGHBORS_INTERVAL_IN_SECONDS=1'
      - 'SHORT_TRANSIENT_FAULT_TIMEOUT_IN_SECONDS=4'
      - 'LONG_TRANSIENT_FAULT_TIMEOUT_IN_SECONDS=20'
      - 'COMPLETE_FAULT_TIMEOUT_IN_SECONDS=40'
      - 'PARTITIONS=50'
      - 'PARTITION_SIZE_LIMIT_IN_BYTES=100000000'
      - 'PARTITION_WCU_LIMIT=180000000'
      - 'PARTITION_RCU_LIMIT=450000000'
      - 'TEST_MODE=true'
      - 'DDC_MOCK_APP_LIMIT={"storageBytes":100000000,"wcu":90000000,"rcu":225000000}'
      - 'DDC_MOCK_ALL_DDC_NODES=${DDC_MOCK_ALL_DDC_NODES}'
    ports:
      - '5002:5002'
      - '8082:8082'
    volumes:
      - ./node-2-p2p-config.json:/config/p2p.json
    depends_on:
      - 'ddc-node-0'
      - 'ddc-node-1'
