name: build-docker-image

on:
  push:
    tags:
      - '*'

env:
  DOCKERHUB_REPOSITORY: cerebellumnetwork
  PACKAGE_NAME: ddc-cli

jobs:
  buildDockerImage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@master
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - uses: ayltai/setup-graalvm@v1
        with:
          java-version: 11
          graalvm-version: 21.1.0
          native-image: true
      - name: Cache build .gradle dir
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle
            .gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/build.gradle.kts') }}
      - name: Gradle Build
        run: ./gradlew build
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ steps.get_version.outputs.VERSION }}
        run: |
          docker build -t $DOCKERHUB_REPOSITORY/$PACKAGE_NAME:$IMAGE_TAG .
          echo "::set-output name=image::$DOCKERHUB_REPOSITORY/$PACKAGE_NAME:$IMAGE_TAG"
          docker push $DOCKERHUB_REPOSITORY/$PACKAGE_NAME:$IMAGE_TAG
