name: build-linux-and-macos-executable

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  buildOnLinux:
    runs-on: [self-hosted, cere-network-xlarge-workers]
    steps:
      - name: Checkout the code
        uses: actions/checkout@master
      - uses: ayltai/setup-graalvm@v1
        with:
          java-version: 11
          graalvm-version: 21.2.0
          native-image: true
      - uses: KengoTODA/actions-setup-docker-compose@main
        name: 'Install docker-compose'
        with:
          version: '1.29.2'
      - name: Cache build .gradle dir
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle
            .gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/build.gradle.kts') }}
      - name: 'Install build dependencies'
        run: sudo apt-get install build-essential libz-dev zlib1g-dev
      - name: Gradle Build
        run: ./gradlew build
      - name: Upload artifacts
        run: mkdir linux-amd64 && cp build/ddc-cli-*-runner linux-amd64/ddc-cli
      - uses: actions/upload-artifact@v2
        with:
          name: ddc-cli-linux-amd64
          path: linux-amd64
          retention-days: 7

  buildOnMac:
    runs-on: [self-hosted, cere-network-xlarge-workers]
    steps:
      - name: Checkout the code
        uses: actions/checkout@master
      - uses: ayltai/setup-graalvm@v1
        with:
          java-version: 11
          graalvm-version: 21.2.0
          native-image: true
      - uses: KengoTODA/actions-setup-docker-compose@main
        name: 'Install docker-compose'
        with:
          version: '1.29.2'
      - name: Cache build .gradle dir
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle
            .gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/build.gradle.kts') }}
      - name: 'Install build dependencies'
        run: xcode-select --install
      - name: Gradle Build
        run: ./gradlew build
      - name: Upload artifacts
        run: mkdir mac-amd64 && cp build/ddc-cli-*-runner mac-amd64/ddc-cli
      - uses: actions/upload-artifact@v2
        with:
          name: ddc-cli-mac-amd64
          path: mac-amd64
